flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    title = StringField('Post Title', validators=(
        [DataRequired(), Length(min=1, max=250)]))

    content = TextAreaField('Post Content', validators=([DataRequired()]))
    submit = SubmitField('Post')

flaskblog/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flaskblog.model import User
from flask_login import current_user
from flaskblog import bcrypt


class RegestrationForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=3, max=20)])

    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[
                             DataRequired(), Length(min=6, max=20)])
    confirm_password = PasswordField(
        'Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Regester')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Username taken, try another one')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email already in use, try another email')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class UpdateForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=3, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    profile_img = FileField('Update Profile Picture',
                            validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    update = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('Username taken, try another one')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError(
                    'Email already in use, try another email')


class RequerstResetForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])

    request = SubmitField('Requerst Password Reset')

    # ! revelaing that an email is not associated with an accout is a security flaw
    # def validate_email(self, email):
    #     user = User.query.filter_by(email=email.data).first()
    #     if user is None:
    #         raise ValidationError('There is no account with this email')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('New Password', validators=[
                             DataRequired(), Length(min=6, max=20)])
    confirm_password = PasswordField(
        'Confirm New Password', validators=[DataRequired(), EqualTo('password')])

    reset = SubmitField('Reset Password')


class ChangePassword(FlaskForm):
    old_password = PasswordField('Old Password', validators=[
        DataRequired(), Length(min=6, max=20)])
    new_password = PasswordField('New Password', validators=[
        DataRequired(), Length(min=6, max=20)])
    confirm_new_password = PasswordField(
        'Confirm New Password', validators=[DataRequired(), EqualTo('new_password')])

    change = SubmitField('Change Password')

    def validate_old_password(self, old_password):
        if not bcrypt.check_password_hash(current_user.password, old_password.data):
            raise ValidationError('Old password does not match, Try again.')

    def validate_new_password(self, new_password):
        if bcrypt.check_password_hash(current_user.password, new_password.data):
            raise ValidationError(
                'New and Old passwords cannot be the same. Chose a different password')

flaskblog/posts/routes.py
from flask import render_template, flash, url_for, redirect, request, abort, Blueprint
from flaskblog import db
from flaskblog.posts.forms import PostForm
from flaskblog.model import Post
from flask_login import current_user, login_required
posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post created', 'success')
        return redirect(url_for('main.home'))
    return render_template('newPost.html', form=form, legend="New Post")


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post updated', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == "GET":
        form.submit.label.text = "Update"
        form.title.data = post.title
        form.content.data = post.content
    return render_template('newPost.html', form=form, legend="Update Post")


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f'Post: "{post.title}" Deleted', 'info')
    page = request.args.get('page')
    if page:
        return redirect(url_for(page))
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint
from flask import render_template, flash, url_for, redirect, request
from flaskblog import bcrypt, db, POSTS_PER_PAGE
from flaskblog.users.forms import RegestrationForm, LoginForm, UpdateForm, RequerstResetForm, ResetPasswordForm, ChangePassword
from flaskblog.model import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog.users.utils import send_reset_email, update_profile_img

users = Blueprint('users', __name__)


@users.route('/regester', methods=['GET', 'POST'])
def regester():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = RegestrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(
            f'Account created for {form.username.data}, You can login now!', 'success')
        return redirect(url_for('users.login'))
    return render_template('regester.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful, Please check email and password', 'error')
    return render_template('login.html', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateForm()
    if form.validate_on_submit():
        if form.profile_img.data:
            picture_file = update_profile_img(
                form.profile_img.data, form.username.data)
            current_user.profile_img = picture_file
            db.session.commit()
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account information updated', 'info')
        redirect(url_for('users.account'))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image = url_for('static', filename='images/profiles/' +
                    current_user.profile_img)
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(author=current_user).order_by(
        Post.post_date.desc()).paginate(per_page=POSTS_PER_PAGE, page=page)
    return render_template('account.html', image=image, form=form, posts=posts)


@users.route('/user/<string:username>')
def user(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first()
    posts = Post.query.filter_by(author=user).order_by(
        Post.post_date.desc()).paginate(per_page=POSTS_PER_PAGE, page=page)
    return render_template('user.html', user=user, posts=posts)


@users.route('/reset/request', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = RequerstResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
        flash('If an account with this email address exists, a password reset message will be sent shortly', 'info')
        return redirect(url_for('main.home'))
    return render_template('requestReset.html', form=form)


@users.route('/reset/password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    user = User.verify_reset_token(token)
    if not user:
        flash('Invalid or Expired Token, Try Again.', 'error')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(
            f'Password updated', 'success')
        return redirect(url_for('users.login'))
    return render_template('passwordReset.html', form=form)


@users.route('/reset', methods=['GET', 'POST'])
@users.route('/reset/password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePassword()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.new_password.data).decode('utf-8')
        current_user.password = hashed_password
        db.session.commit()
        flash(
            f'Password Changed', 'success')
        return redirect(url_for('users.account'))
    return render_template('changePassword.html', form=form)

flaskblog/templates/about.html
{%extends "layout.html"%} {% block style%}
<link rel="stylesheet" href="{{url_for('static', filename='styles/about.css') }}" />
{%endblock style%} {% block title%} About {% endblock title%} {%block main%}
<h1>About Me:</h1>
<div class="bio">
    <p>
        Hey there, welcome to my first ever website that i made. Yes I've made pages
        before, whitch you can check out on my
        <a href="https://github.com/Hank2q" target="_blank">GitHub</a>, but this is
        the first website I made with backend using Flask framework in python. <br />
        This is just a simple page where I might post some thoughts I have. I'm also
        posting some fun things which I made.<br />
        If you're wondering about the picture below, I also made it in Adobe
        Illustrator, I like bears especially polar bares and I'm using this one as my
        logo for now, that is untill i get bored and make a new one.
    </p>
    <img src="static/images/logoSmall.png" alt="Polar Code Logo" />
</div>
{%endblock main%}

flaskblog/templates/account.html
{%extends "layout.html"%} {% block title%} Account {% endblock title%} {% block
style%}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/post.css') }}" />
<link
    rel="stylesheet"
    href="{{ url_for('static', filename='styles/inputs.css') }}"
/>
<link rel="stylesheet" href="{{ url_for('static', filename='styles/user.css') }}" />
<link
    rel="stylesheet"
    href="{{ url_for('static', filename='styles/account.css') }}"
/>
{%endblock style%} {%block main%}
<div class="container">
    <div class="account-info">
        <div class="img-cont">
            <img class="profile-pic" src="{{image}}" alt="Profile Picture" />
            <button class="edit-pic"><i class="fas fa-edit"></i> Change</button>
        </div>
        <div class="text">
            <h1 class="display-username">{{current_user.username}}</h1>
            <h4 class="display-email">{{current_user.email}}</h4>
        </div>
        <button class="edit"><i class="fas fa-edit"></i> Edit</button>
    </div>
    <div class="update-container invisible">
        <form id="update-form" action="" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag()}}
            <div class="username-container feild">
                {{form.username.label(class='user-label')}} {%if
                form.username.errors%} {{form.username(class='username
                input-error')}} {%for error in form.username.errors%}
                <span class="error-msg">{{error}}</span>
                {% endfor %} {%else%} {{form.username(class='username')}} {%endif%}
            </div>
            <div class="email-container feild">
                {{form.email.label()}} {%if form.email.errors%}
                {{form.email(class='email input-error')}} {%for error in
                form.email.errors%}
                <span class="error-msg">{{error}}</span>
                {% endfor %} {%else%} {{form.email(class='email')}} {%endif%}
            </div>
            {{form.profile_img.label()}}<br />
            {%if form.profile_img.errors%} {{form.profile_img(class='profile_img
            input-error')}}<br />
            {%for error in form.profile_img.errors%}
            <span class="error-msg">{{error}}</span>
            {% endfor %} {%else%} {{form.profile_img()}}<br />
            <img id="output" class="invisible" />
            {%endif%}
            <a href="{{url_for('users.change_password')}}">Change Password</a>
            {{ form.update(class='registerbtn')}}
        </form>
        <button class="closebtn registerbtn">Close</button>
    </div>
</div>
<div class="posts-container">
    <div class="list">
        <h3>Posts</h3>
        <i class="fas fa-caret-left"></i>
    </div>
    <div data-pages="{{posts.pages}}" class="posts">
        {% for post in posts.items%}
        <div class="post" id="{{post.id}}">
            <h3>
                <a
                    class="post-title"
                    href="{{url_for('posts.post', post_id=post.id)}}"
                    >{{post.title}}</a
                >
            </h3>
            <div class="edit-post">
                <i class="menu-btn fas fa-ellipsis-h"></i>
                <ul class="options">
                    <a href="{{url_for('posts.update_post', post_id=post.id)}}">
                        <li class="option">
                            <i class="fas fa-pen"> Edit</i>
                        </li>
                    </a>
                    <i class="delete-post">
                        <li class="option">
                            <i class="fas fa-trash-alt"> Delete</i>
                        </li>
                    </i>
                    <form
                        id="delete-{{post.id}}"
                        action="{{url_for('posts.delete_post', post_id=post.id, page='users.account')}}"
                        method="POST"
                    ></form>
                </ul>
            </div>
            <h5>{{post.post_date.strftime("%d %b, %Y") }}</h5>
            <p>{{post.content}}</p>
        </div>
        {%endfor%}
    </div>
    {% if posts.pages > 1%}
    <div class="pages invisible">
        {%for page_num in posts.iter_pages(left_current=2, right_current=2)%} {%if
        page_num %} {%if page_num == posts.page%}
        <a class="page-num active" href="{{url_for('users.account', page=page_num)}}"
            >{{page_num}}</a
        >
        {%else%}
        <a class="page-num" href="{{url_for('users.account', page=page_num)}}"
            >{{page_num}}</a
        >
        {%endif%} {%else%} ... {%endif%} {%endfor%}
    </div>
    {% endif %}
</div>
{%endblock main%} {%block script%}
<script src="{{ url_for('static', filename='javascripts/sweetalert2.all.min.js') }}"></script>
<script src="{{ url_for('static', filename='javascripts/postMenu.js') }}"></script>
<script src="{{ url_for('static', filename='javascripts/account.js') }}"></script>

{%endblock script%}

flaskblog/templates/changePassword.html
{% extends "layout.html"%} {%block title%} Password Reset {%endblock title%} {%block
style%}
<link rel="stylesheet" href="{{url_for('static', filename='styles/inputs.css')}}" />
{%endblock style%} {%block main%}
<div class="input-container">
    <form action="" method="post">
        {{ form.hidden_tag()}}
        <div class="password-container feild">
            {{form.old_password.label()}} {%if form.old_password.errors%}
            {{form.old_password(class='input-error')}} {%for error in
            form.old_password.errors%}
            <span class="error-msg">{{error}}</span>
            {% endfor %} {%else%} {{form.old_password(class='password')}} {%endif%}
        </div>
        <div class="password-container feild">
            {{form.new_password.label()}} {%if form.new_password.errors%}
            {{form.new_password(class='input-error')}} {%for error in
            form.new_password.errors%}
            <span class="error-msg">{{error}}</span>
            {% endfor %} {%else%} {{form.new_password(class='password')}} {%endif%}
        </div>
        <div class="confirm-container feild">
            {{form.confirm_new_password.label()}} {%if
            form.confirm_new_password.errors%}
            {{form.confirm_new_password(class='input-error')}} {%for error in
            form.confirm_new_password.errors%}
            <span class="error-msg">{{error}}</span>
            {% endfor %} {%else%} {{form.confirm_new_password()}} {%endif%}
        </div>
        {{form.change(class='registerbtn')}}
    </form>
    <a href="{{url_for('users.account')}}"
        ><button class="closebtn registerbtn">Cancel</button></a
    >
</div>
{%endblock main%}

flaskblog/templates/contact.html
{%extends "layout.html"%} {% block title%} Contact {% endblock title%} {%block main%}
<h1>Reach Me At:</h1>
<ul>
    <li>
        <h2>
            Email:
            <a href="mailto: python.hank@gmail.com">python.hank@gmail.com</a>
        </h2>
    </li>
    <br />
    <li>
        <h2>
            GitHub:
            <a href="https://github.com/Hank2q" target="_blank">github.com/Hank2q</a>
        </h2>
    </li>
</ul>
{%endblock main%}

flaskblog/templates/home.html
{%extends "layout.html"%} {% block style%}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/post.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}" />
{%endblock style%} {%block title%} Home {% endblock title%} {% block main %}
<div data-pages="{{posts.pages}}" class="posts">
    {% for post in posts.items%}
    <div class="post" id="{{post.id}}">
        <div class="user-info">
            <div class="img-cont">
                <img
                    class="circle"
                    src="{{url_for('static', filename='images/profiles/' + post.author.profile_img)}}"
                />
            </div>
            <div class="text">
                <h5>
                    {%if current_user == post.author%}
                    <a href="{{url_for('users.account')}}"
                        >{{post.author.username}}</a
                    >
                    {%else%}
                    <a
                        href="{{url_for('users.user', username=post.author.username)}}"
                        >{{post.author.username}}</a
                    >
                    {%endif%}
                </h5>
                <h5>{{post.post_date.strftime("%d %b, %Y") }}</h5>
            </div>
        </div>
        {%if current_user == post.author%}
        <div class="edit-post">
            <i class="menu-btn fas fa-ellipsis-h"></i>
            <ul class="options">
                <a href="{{url_for('posts.update_post', post_id=post.id)}}">
                    <li class="option">
                        <i class="fas fa-pen"> Edit</i>
                    </li>
                </a>
                <i class="delete-post">
                    <li class="option">
                        <i class="fas fa-trash-alt"> Delete</i>
                    </li>
                </i>
                <form
                    id="delete-{{post.id}}"
                    action="{{url_for('posts.delete_post', post_id=post.id, page='main.home')}}"
                    method="POST"
                ></form>
            </ul>
        </div>
        {%endif%}
        <h3>
            <a class="post-title" href="{{url_for('posts.post', post_id=post.id)}}"
                >{{post.title}}</a
            >
        </h3>
        <p>{{post.content}}</p>
    </div>
    {%endfor%}
</div>
<div class="bottom">
    <p class="no-more"></p>
    <img
        class="loader"
        src="{{url_for('static', filename='images/loader.svg')}}"
        alt=""
    />
</div>
<a href="#"
    ><button class="to-top"><i class="fas fa-chevron-up"></i></button
></a>
{%endblock main%} {%block script%}
<script src="{{ url_for('static', filename='javascripts/sweetalert2.all.min.js') }}"></script>
<script
    defer
    src="{{ url_for('static', filename='javascripts/scrollLoad.js')}}"
></script>
<script
    defer
    src="{{ url_for('static', filename='javascripts/postMenu.js') }}"
></script>
{%endblock script%}

flaskblog/templates/login.html
{% extends "layout.html"%} {%block title%} Login {%endblock title%} {%block style%}
<link rel="stylesheet" href="{{url_for('static', filename='styles/inputs.css')}}" />
{%endblock style%} {%block main%}

<div class="input-container">
    <form action="" method="post">
        {{ form.hidden_tag()}}
        <div class="email-container feild">
            {{form.email.label(class='user-label')}} {%if form.email.errors%}
            {{form.email(class='user-label input-error')}} {%for error in
            form.email.errors%}
            <span class="error-msg">{{error}}</span>
            {% endfor %} {%else%} {{form.email(class='email')}} {%endif%}
        </div>
        <div class="password-container feild">
            {{form.password.label(class='user-label')}} {%if form.password.errors%}
            {{form.password(class='user-label input-error')}} {%for error in
            form.password.errors%}
            <span class="error-msg">{{error}}</span>
            {% endfor %} {%else%} {{form.password(class='password')}} {%endif%}
        </div>
        {{form.remember.label()}} {{ form.remember()}} {{
        form.submit(class='registerbtn')}}
    </form>
</div>
<div>
    <p><a href="{{url_for('users.reset_request')}}">Forgot Password</a></p>
</div>

<div class="footnote">
    <p>Don't have an account? <a href="/regester">Regester Here</a></p>
</div>
{%endblock main%}

flaskblog/templates/more.html
{% for post in posts.items%}
<div class="post" id="{{post.id}}">
    <div class="user-info">
        <div class="img-cont">
            <img
                class="circle"
                src="{{url_for('static', filename='images/profiles/' + post.author.profile_img)}}"
            />
        </div>
        <div class="text">
            <h5>
                {%if current_user == post.author%}
                <a href="{{url_for('users.account')}}">{{post.author.username}}</a>
                {%else%}
                <a href="{{url_for('users.user', username=post.author.username)}}"
                    >{{post.author.username}}</a
                >
                {%endif%}
            </h5>
            <h5>{{post.post_date.strftime("%d %b, %Y") }}</h5>
        </div>
    </div>
    {%if current_user == post.author%}
    <div class="edit-post">
        <i class="menu-btn fas fa-ellipsis-h"></i>
        <ul class="options">
            <a href="{{url_for('posts.update_post', post_id=post.id)}}">
                <li class="option">
                    <i class="fas fa-pen"> Edit</i>
                </li>
            </a>
            <i class="delete-post">
                <li class="option">
                    <i class="fas fa-trash-alt"> Delete</i>
                </li>
            </i>
            <form
                action="{{url_for('posts.delete_post', post_id=post.id, page='main.home')}}"
                method="POST"
            >
                <input
                    style="display: none"
                    id="delete-{{post.id}}"
                    type="submit"
                    value="delete"
                />
            </form>
        </ul>
    </div>
    {%endif%}
    <h3>
        <a class="post-title" href="{{url_for('posts.post', post_id=post.id)}}"
            >{{post.title}}</a
        >
    </h3>
    <p>{{post.content}}</p>
</div>
{%endfor%}

flaskblog/templates/post.html
{%extends "layout.html"%} {% block style%}
<link
    rel="stylesheet"
    href="{{
url_for('static', filename='styles/post.css') }}"
/>
{%endblock style%} {%block title%} {{title}} {% endblock title%} {% block main %}
<div class="post" id="{{post.id}}">
    <div class="user-info">
        <div class="img-cont">
            <img
                class="circle"
                src="{{url_for('static', filename='images/profiles/' + post.author.profile_img)}}"
            />
        </div>
        <div class="text">
            <h5>
                {%if current_user == post.author%}
                <a href="{{url_for('users.account')}}">{{post.author.username}}</a>
                {%else%}
                <a href="{{url_for('users.user', username=post.author.username)}}"
                    >{{post.author.username}}</a
                >
                {%endif%}
            </h5>
            <h5>{{post.post_date.strftime("%d %b, %Y") }}</h5>
        </div>
    </div>
    {%if current_user == post.author%}
    <div class="edit-post">
        <i class="menu-btn fas fa-ellipsis-h"></i>
        <ul class="options">
            <a href="{{url_for('posts.update_post', post_id=post.id)}}">
                <li class="option">
                    <i class="fas fa-pen"> Edit</i>
                </li>
            </a>
            <i class="delete-post">
                <li class="option">
                    <i class="fas fa-trash-alt"> Delete</i>
                </li>
            </i>
            <form
                id="delete-{{post.id}}"
                action="{{url_for('posts.delete_post', post_id=post.id, page='users.account')}}"
                method="POST"
            ></form>
        </ul>
    </div>
    {%endif%}
    <h3 class="post-title">{{post.title}}</h3>
    <p>{{post.content}}</p>
</div>

{%endblock main%} {%block script%}
<script src="{{ url_for('static', filename='javascripts/sweetalert2.all.min.js') }}"></script>
<script
    defer
    src="{{ url_for('static', filename='javascripts/postMenu.js') }}"
></script>
{%endblock script%}

flaskblog/templates/requestReset.html
{% extends "layout.html"%} {%block title%} Request Password Reset {%endblock title%}
{%block style%}
<link rel="stylesheet" href="{{url_for('static', filename='styles/inputs.css')}}" />
{%endblock style%} {%block main%}
<div class="input-container">
    <form action="" method="post">
        {{ form.hidden_tag()}}
        <div class="email-container feild">
            {{form.email.label()}} {%if form.email.errors%}
            {{form.email(class='input-error')}} {%for error in form.email.errors%}
            <span class="error-msg">{{error}}</span>
            {% endfor %} {%else%} {{form.email(class='email')}} {%endif%}
        </div>
        {{form.request(class='registerbtn')}}
    </form>
</div>
{%endblock main%}

flaskblog/templates/user.html
{%extends "layout.html"%} {% block title%} {{user.username}} {% endblock title%} {%
block style%}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/post.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='styles/user.css') }}" />
{%endblock style%} {%block main%}
<div class="container">
    <div class="account-info">
        <div class="img-cont">
            <img
                class="profile-pic"
                src="{{url_for('static', filename='images/profiles/' + user.profile_img)}}"
                alt="Profile Picture"
            />
        </div>
        <div class="text">
            <h1 class="display-username">{{user.username}}</h1>
        </div>
    </div>
</div>

{% for post in posts.items%}
<div class="post">
    <h3 class="post-title">
        <a href="{{url_for('posts.post', post_id=post.id)}}">{{post.title}}</a>
    </h3>
    <h5>{{post.post_date.strftime("%d %b, %Y") }}</h5>
    <p>{{post.content}}</p>
</div>
{%endfor%} {% if posts.pages > 1%} {%for page_num in posts.iter_pages(left_current=2,
right_current=2)%} {%if page_num %} {%if page_num == posts.page%}
<a
    class="page-num active"
    href="{{url_for('users.user', username=user.username,page=page_num)}}"
    >{{page_num}}</a
>
{%else%}
<a
    class="page-num"
    href="{{url_for('users.user', username=user.username,page=page_num)}}"
    >{{page_num}}</a
>
{%endif%} {%else%} ... {%endif%} {%endfor%} {%endif%} {%endblock main%}